name: Auto Merge to Preprod

on:
  workflow_dispatch:

jobs:
  merge:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ github.token }}

    - name: Configure Git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    - name: Fetch and Merge branches
      run: |
        echo "Branche source à fusionner : ${{ github.ref_name }}"
        
        git checkout preprod
        
        git pull origin preprod
        
        git merge origin/${{ github.ref_name }} --no-ff -m "Automated merge: '${{ github.ref_name }}' into preprod"
        
        git push origin preprod
